### ISSUE TITLE
Do not package the mongodb data dir

### ISSUE THREAD

**Issue by ChALkeR** [JamenMarz/HTTP-Goose#2]
*Disclaimer: I do not use the package, this was found during automated npm packages downloading.*

Your current package size is 3.1 MiB packed, **3.1 GiB** unpacked. 3.1 GiB of that are inside the `test/data` dir. I think that this probably got packed to the release by mistake.

You could add that dir to the `.gitignore`.

**Comment by JamenMarz** [comment]
Wow, really?  This was on NPM, correct?

I believe that have a alternative `.npmignore` as well?

**Comment by ChALkeR** [comment]
Yes, that's on npm.
If there is no `.npmignore`, `.gitignore` is used instead.
If there is `.npmignore`, npm ignores `.gitignore` and uses `.npmignore` afaik.

**Comment by ChALkeR** [comment]
If you want to remove you package from npm, you could run [npm unpublish](https://docs.npmjs.com/cli/unpublish).

**Comment by JamenMarz** [comment]
@ChaLkeR The MongoDB isn't in my local version, perhaps that was just an error when I first published...  I'll just add it to the `.gitignore` to stop future accidents like this, and also publish the new one that doesn't contain the MongoDB data.

**Comment by JamenMarz** [comment]
Whoops, misspelled "fixes" in that commit...  Lol.

**Comment by JamenMarz** [comment]
Publishing the local version that doesn't have the MongoDB data.
